import{chromium}from'playwright';import fs from'node:fs/promises';import path from'node:path';import{createHash}from'node:crypto';
const out=path.resolve('../renders/life');await fs.mkdir(out,{recursive:true});const browser=await chromium.launch({executablePath:'C:/Users/limou/AppData/Local/ms-playwright/chromium-1237/chrome-win64/chrome.exe',headless:true,args:['--enable-unsafe-webgpu','--use-angle=d3d11','--disable-background-timer-throttling','--disable-renderer-backgrounding']});const page=await browser.newPage({viewport:{width:1600,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());if(m.type()==='info')console.log(m.text());});
const report={timestamp:new Date().toISOString(),scope:'Isolated desktop hardware Chromium; full source geometry, native1600x1000 DPR1,4MSAA',checks:{},errors};
try{
 await page.goto('http://127.0.0.1:4173/?debug=1');await page.waitForFunction(()=>window.__cityTest?.ready||!document.getElementById('error').hidden,undefined,{timeout:120000});if(!await page.evaluate(()=>!!window.__cityTest))throw Error(await page.locator('#error-message').textContent());
 await page.evaluate(()=>{window.__cityTest.life.setPaused(true);window.__lifeDraws=window.__cityTest.auditLifeDraws();});report.initial=await page.evaluate(()=>window.__cityTest.getState());report.sourceHash=report.initial.sourceHash;
 await page.addStyleTag({content:'#loading,#pause,#header,#intro,#location,#compass,#walk-hint,#reticle {display:none!important}'});
 const snapshots=await page.evaluate(()=>{const api=window.__cityTest,frames=[];for(let i=0;i<=200;i++){if(i)api.life.step(.1);frames.push(api.lifeSnapshot());}return frames;});
 const actors=snapshots[0].actors.map(a=>({id:a.id,type:a.type,prototype:a.prototype,sourceInstanceId:a.sourceInstanceId,asset:a.asset,scale:a.scale,materialColors:a.materialColors,samples:snapshots.map((s,i)=>{const p=s.actors.find(b=>b.id===a.id);return{time:i/10,position:p.position,rotation:p.rotation,walkTime:p.walkTime,idleTime:p.idleTime,walkWeight:p.walkWeight,idleWeight:p.idleWeight};})}));
 await fs.mkdir('../validation',{recursive:true});if(!process.env.CITY_KEEP_CAPTURE)await fs.writeFile('../validation/city_life_samples.json',JSON.stringify({fps:30,sampleHz:10,duration:20,sourceHash:report.sourceHash,actors}));report.captureSHA256=createHash('sha256').update(await fs.readFile('../validation/city_life_samples.json')).digest('hex');console.log('Blender samples preserved',report.captureSHA256);
 report.checks.exportedAnimation={status:'passed',duration:20,samples:201,actors:actors.length};
 report.checks.clipDeformation=[];for(let i=0;i<8;i++){report.checks.clipDeformation.push(await page.evaluate(()=>{const a=window.__cityTest;const result=a.inspectPedestrian('pedestrian_002');a.life.step(1/8);return result;}));}
 const start=await page.evaluate(()=>window.__cityTest.lifeSnapshot());const longRun=await page.evaluate(()=>{const api=window.__cityTest,checks=[],stuck={},before=api.lifeSnapshot();for(let i=0;i<1200;i++){api.life.step(.1);if(i%50===0){const s=api.lifeSnapshot(),p=s.actors.filter(a=>a.type==='pedestrian');let nearest=Infinity,pair;for(let a=0;a<p.length;a++)for(let b=a+1;b<p.length;b++){const d=Math.hypot(p[a].position[0]-p[b].position[0],p[a].position[2]-p[b].position[2]);if(d<nearest){nearest=d;pair=[p[a].id,p[b].id];}}checks.push({time:s.time,stats:api.life.stats(),nearest,pair});}}return{checks,after:api.lifeSnapshot()};});report.longRun=longRun;report.checks.pedestrianRoutes={status:longRun.checks.every(c=>!c.stats.pedestrians.unsafe.length&&c.nearest>=.8&&!c.stats.pedestrians.stalled.length)?'passed':'failed',samples:longRun.checks.length,seconds:120,minimumSeparation:Math.min(...longRun.checks.map(c=>c.nearest)),maximumStationarySeconds:Math.max(...longRun.checks.map(c=>c.stats.pedestrians.maximumStationarySeconds))};
 for(const id of ['lake','park','downtown','station']){const state=await page.evaluate(()=>window.__cityTest.lifeSnapshot());const group=id==='lake'?0:id==='park'?8:id==='downtown'?16:32;const actor=state.actors.find(a=>a.id===`pedestrian_${String(group+2).padStart(3,'0')}`),f=[Math.sin(actor.rotation),Math.cos(actor.rotation)];const position=[actor.position[0]+f[0]*7,actor.position[1],actor.position[2]+f[1]*7];const yaw=Math.atan2(f[0],f[1]);await page.evaluate(({position,yaw})=>window.__cityTest.singleFrameAt(position,yaw,.015),{position,yaw});await page.screenshot({path:path.join(out,id+'-walk-a.png')});await page.evaluate(()=>window.__cityTest.life.step(.4));await page.evaluate(({position,yaw})=>window.__cityTest.singleFrameAt(position,yaw,.015),{position,yaw});await page.screenshot({path:path.join(out,id+'-walk-b.png')});}
 report.shadowReference=await page.evaluate(()=>window.__cityTest.auditLifeShadows());report.checks.shadowDepthUnion={status:report.shadowReference.passed?'passed':'failed',...report.shadowReference};console.log('Shadow audit',report.shadowReference);
 await page.evaluate(()=>{window.__cityTest.resumeFrames();window.__cityTest.life.setPaused(false);window.__cityTest.walk();});await page.waitForTimeout(500);const stationaryA=await page.evaluate(()=>window.__cityTest.getState()),snapA=await page.evaluate(()=>window.__cityTest.lifeSnapshot());await page.waitForTimeout(3000);const stationaryB=await page.evaluate(()=>window.__cityTest.getState()),snapB=await page.evaluate(()=>window.__cityTest.lifeSnapshot());report.checks.stationaryCamera={status:stationaryB.life.time>stationaryA.life.time+2?'passed':'failed',timeDelta:stationaryB.life.time-stationaryA.life.time,staticShadowPassDelta:stationaryB.shadowStats.staticPasses-stationaryA.shadowStats.staticPasses,dynamicShadowPassDelta:stationaryB.shadowStats.dynamicPasses-stationaryA.shadowStats.dynamicPasses,changedActorPositions:snapB.actors.filter((a,i)=>JSON.stringify(a.position)!==JSON.stringify(snapA.actors[i].position)).length};
 const poses=report.checks.clipDeformation;report.checks.canonicalSkinning={status:poses.every(p=>p.bones===49&&p.meshes===3&&p.triangles===5622&&Math.abs(p.lowestSoleGap)<.03)&&new Set(poses.map(p=>p.walkTime)).size===poses.length?'passed':'failed',samples:poses.length,maximumSoleDeviation:Math.max(...poses.map(p=>Math.abs(p.lowestSoleGap)))};
 const draws=await page.evaluate(()=>window.__lifeDraws);report.checks.dynamicPassMembership={status:['beauty:pedestrian','beauty:vehicle','reflection:pedestrian','reflection:vehicle','dynamic-shadow:pedestrian','dynamic-shadow:vehicle'].every(key=>draws[key]>0)?'passed':'failed',counts:draws};
 report.final=await page.evaluate(()=>window.__cityTest.getState());
}catch(e){report.failure=String(e);console.error(e);process.exitCode=1;}finally{await fs.writeFile('life_validation.json',JSON.stringify(report,null,2));await browser.close();if(Object.values(report.checks).some(c=>c.status==='failed')||errors.length||report.failure)process.exitCode=1;}
